# Generated by Django 4.2.1 on 2023-05-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='Dirección')),
                ('country', models.CharField(max_length=50, verbose_name='País')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Imagen')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('description', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Inmueble',
                'verbose_name_plural': 'Inmuebles',
            },
        ),
    ]
