# Generated by Django 4.2.1 on 2023-05-04 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_company_options_property_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='property', to='property.company'),
            preserve_default=False,
        ),
    ]
