# Generated by Django 4.2.1 on 2023-05-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_alter_comment_options_alter_property_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='calification_avg',
            field=models.FloatField(default=0, verbose_name='Promedio de Calificaciones'),
        ),
        migrations.AddField(
            model_name='property',
            name='calification_count',
            field=models.IntegerField(default=0, verbose_name='Cantidad de Calificaciones'),
        ),
    ]
