# Generated by Django 4.2.1 on 2023-05-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_alter_property_calification_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='calification_sum',
            field=models.PositiveIntegerField(default=0, verbose_name='Suma de Calificaciones'),
        ),
        migrations.AlterField(
            model_name='property',
            name='calification_count',
            field=models.IntegerField(default=0, verbose_name='Cantidad de Calificaciones'),
        ),
    ]
